### ISSUE TITLE
Resetting sigma throws index out of range

### ISSUE THREAD

**Issue by simonhughes22** [llazzaro/lsa_python#1]
len(sigma) is bound by the smaller of the rows and cols of the matrix. If you pass the lsa algorithm a matrix with rows > cols, the code throws an index out of bounds exception. This code will fix:

smallerBound = min(rows, cols)
for index in xrange(smallerBound - dimensions, smallerBound):
    sigma[index]=0

Thanks for providing such a useful piece of software

**Comment by llazzaro** [comment]
thanks for reporting this issue!!

this issue was fixed on develop branch.
 https://github.com/llazzaro/lsa_python/commit/bbec04161230d7db5ee196a1e61acbaf2ab50b25
